spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.79:3306/SpringCloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
